# 1. download the base image (python 3.9 slim)
FROM python:3.9-slim

# 2. set the working directory inside the container
WORKDIR /app


# 3. install the required Python packages (pandas)
RUN pip install pandas

# 4. copy the code and CSV file from your machine to the container
COPY app.py .
COPY Traffic.csv .

# 5. the command to run the application when the container starts
CMD ["python", "app.py"]